apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.daemonSet.name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: invoker
  template:
    metadata:
      labels:
        app: invoker
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      initContainers:
      - name: init
        image: {{ .Values.dockerMirror }}/{{ .Values.kubectlImage }}
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        command: ["sh", "-c", "kubectl label pod $POD_NAME node=$NODE_NAME --namespace=$NAMESPACE"]
      containers:
      - name: invoker
        image: {{ .Values.dockerRegistry }}/{{ .Values.invokerImage }}
        ports:
        - containerPort: 8080
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName