apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Values.role.name }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["pods", "services"]
  verbs: ["create", "get", "list", "watch", "delete", "patch"]
- apiGroups: ["apps"]
  resources: ["daemonsets", "deployments"]
  verbs: ["create", "get", "list", "watch", "delete", "patch"]